name: Build libft.a

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build simple libft
        run: make
      - name: build bonus libft
        run: make bonus
      - name: build full libft
        run: make all
      - name: clean
        run: make fclean
