name: Norme, Compilation & Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build simple libft
        run: make
      - name: build bonus libft
        run: make bonus
      - name: build full libft
        run: make full
      - name: clean
        run: make fclean
  warmachine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init
      - name: Install 
        run: sudo apt-get install -y diff python3 && python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette
      - name: GradeMe
        run: cd war-machine && ./grademe.sh -u -m ; ./grademe.sh -u -m
      - name: Deepthought
        run: cat war-machine/deepthought
#      - name: Is Valid ?
#        run: cat war-machine/deepthought | grep KO