name: Build

on: [push, pull_request]

jobs:
  mandatory:
    runs-on: ubuntu-latest
    name: Build Mandatory Part
    permissions:
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Make
        run: make
      - name: Clean
        run: make clean
      - name: Clean Executable
        run: make fclean
  bonus:
    runs-on: ubuntu-latest
    name: Build Bonus Part
    permissions:
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Make Bonus
        run: make bonus
      - name: Clean
        run: make clean
      - name: Clean Executable
        run: make fclean
  custom:
    runs-on: ubuntu-latest
    name: Build Custom Part
    permissions:
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Make Full
        run: make full
      - name: Clean
        run: make clean
      - name: Clean Executable
        run: make fclean
