name: Unit Test

on: [push, pull_request]

jobs:
  testers_linux:
    runs-on: ubuntu-latest
    name: Tester linux
    permissions:
      checks: write
    env:
      TERM: linux
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Progs for Tester
        run: |
          sudo apt update
          sudo apt-get install -y bash diffutils python3 pip gcc clang build-essential valgrind
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      - name: Tester WARMACHINE Init
        run: |
          cd warmachine
          bash grademe.sh -u -m
      - name: Tester WARMACHINE Execute
        run: |
          cd warmachine
          bash grademe.sh -u -m
        shell: bash
      - name: Tester WARMACHINE Deepthought
        run: cat warmachine/deepthought
      - name: Tester TRIPOUILLE Init
        run: |
          cd tripouille
          sudo git checkout master
          sudo git pull origin master
      - name: Tester TRIPOUILLE Execute
        run: |
          cd tripouille 
          sudo make a
      - name: One WARMACHINE test passed at least ?
        run: |
          cat warmachine/deepthought | grep OK

  testers_macos:
    runs-on: macos-latest
    name: Tester macOS
    env:
      TERM: xterm-color
    permissions:
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Homebrew & pyenv
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          /usr/local/bin/brew install pyenv
          pyenv init
        continue-on-error: true
      - name: Install Progs for Tester
        run: |
          pyenv install 3.7.9
          pyenv global 3.7.9
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
        continue-on-error: true
      - name: Tester WARMACHINE Init
        run: |
          cd warmachine
          ./grademe.sh -u -m
      - name: Tester WARMACHINE Execute
        run: |
          cd warmachine
          ./grademe.sh -u -m
        shell: bash
      - name: Tester WARMACHINE Deepthought
        run: cat warmachine/deepthought
      # - name: Tester TRIPOUILLE Init
      #   run: |
      #     cd tripouille
      #     git checkout master
      #     git pull origin master
      - name: All WARMACHINE test passed ?
        run: |
          if [ ! cat warmachine/deepthought | grep KO ]; then echo ::set-output name=status::failure; else echo ::set-output name=status::success; fi
        continue-on-error: true
        shell: bash
      - name: Tester TRIPOUILLE Mandatory
        run: |
          cd tripouille
          make a > deepthought
        shell: bash
      - name: Tester TRIPOUILLE Bonus
        run: |
          cd tripouille
          make b > deepthought_bonus
        shell: bash
        continue-on-error: true
      - name: All TRIPOUILLE test Mandatory passed ?
        run: |
          if [ ! cat tripouille/deepthought | grep KO ]; then echo ::set-output name=status::failure; else echo ::set-output name=status::success; fi
        continue-on-error: true
        shell: bash
      - name: All TRIPOUILLE test Bonus passed ?
        run: |
          if [ ! cat tripouille/deepthought_bonus | grep KO ]; then echo ::set-output name=status::failure; else echo ::set-output name=status::success; fi
        continue-on-error: true
        shell: bash
