name: Unit Test

on: [push, pull_request]

env:
  TERM: linux

jobs:
  warmachine:
    runs-on: ubuntu-latest
    name: Tester Warmachine
    permissions:
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Install Progs for Tester
        run: sudo apt-get install -y bash diffutils python3 gcc clang build-essential && python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette
      - name: Tester Init
        run: cd warmachine && ./grademe.sh -u -m
      - name: Tester Execute
        run: cd warmachine && bash grademe.sh -u -m
      - name: Tester Deepthought
        run: cat warmachine/deepthought
#      - name: Is Valid ?
#        run: cat war-machine/deepthought | grep KO
  tripouille:
    runs-on: ubuntu-latest
    name: Tester Tripouille
    permissions:
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Checkout Tester
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init
      - name: Tester Init
        run: cd tripouille && sudo git checkout master && sudo git pull origin master
      - name: Tester Execute
        run: cd tripouille && sudo make a
