name: Checker - War-Machine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init
      - name: GradeMe
        run: cd war-machine && ./grademe.sh -u -m ; ./grademe.sh -u -m
      - name: Deepthought
        run: cat war-machine/deepthought
      - name: Is Valid ?
        run: cat war-machine/deepthought | grep OK

